"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var BaseModel_model_1 = require("../../../../model/core/BaseModel.model");
var MstPaper_model_1 = require("../../../../model/core/MstPaper.model");
/**
 * Created by ASUS on 6/5/2017.
 */
var ProductModel = (function (_super) {
    __extends(ProductModel, _super);
    function ProductModel() {
        _super.apply(this, arguments);
    }
    ProductModel.prototype.setProduct = function (data) {
        this.id = data["id"];
        this.createdUser = data["createdUser"];
        this.updatedUser = data["updatedUser"];
        this.createdDate = data["createdDate"] != undefined ? new Date(data["createdDate"]) : undefined;
        this.updatedDate = data["updatedDate"] != undefined ? new Date(data["updatedDate"]) : undefined;
        this.productName = data["productName"];
        this.productType = data["productType"];
        this.productCode = data["productCode"];
        this.specs = data["specs"];
        this.application = data["application"];
        this.memo1 = data["memo1"];
        this.memo2 = data["memo2"];
        this.memo3 = data["memo3"];
        this.sizeH = data["sizeH"];
        this.sizeD = data["sizeD"];
        this.sizeW = data["sizeW"];
        this.paperNameId = data["paperNameId"];
        this.paperWeight = data["paperWeight"];
        this.paperSizeH = data["paperSizeH"];
        this.paperSizeW = data["paperSizeW"];
        this.cutPaperSizeH = data["cutPaperSizeH"];
        this.cutPaperSizeW = data["cutPaperSizeW"];
        this.blankPaperSizeH = data["blankPaperSizeH"];
        this.blankPaperSizeW = data["blankPaperSizeW"];
        this.paperId = data["paperId"];
        this.takenNumber = data["takenNumber"];
        this.impositionNumber = data["impositionNumber"];
        this.colorFSelect = data["colorFSelect"];
        this.colorBSelect = data["colorBSelect"];
        this.specialColorF = data["specialColorF"];
        this.specialColorB = data["specialColorB"];
        this.printMethod = data["printMethod"];
        this.colorIdF = data["colorIdF"];
        this.colorIdB = data["colorIdB"];
        this.surfaceTreatmentIdF = data["surfaceTreatmentIdF"];
        this.surfaceTreatmentIdB = data["surfaceTreatmentIdB"];
        this.embossingID = data["embossingID"];
        this.laminationFlute = data["laminationFlute"];
        this.laminationMediumBasicWeight = data["laminationMediumBasicWeight"];
        this.laminationMediumThroughWage = data["laminationMediumThroughWage"];
        this.laminationBackBasicWeight = data["laminationBackBasicWeight"];
        this.laminationBackThroughWage = data["laminationBackThroughWage"];
        this.laminationNumber = data["laminationNumber"];
        this.laminationWidth = data["laminationWidth"];
        this.laminationCuttingFlow = data["laminationCuttingFlow"];
        this.dieCuttingId = data["dieCuttingId"];
        this.dieCuttingThroughNumber = data["dieCuttingThroughNumber"];
        this.dieCuttingWeight = data["dieCuttingWeight"];
        this.stampingId = data["stampingId"];
        this.stampingProcessingType = data["stampingProcessingType"];
        this.stampingSizeW1 = data["stampingSizeW1"];
        this.stampingSizeW2 = data["stampingSizeW2"];
        this.stampingSizeW3 = data["stampingSizeW3"];
        this.stampingSizeW4 = data["stampingSizeW4"];
        this.stampingSizeH1 = data["stampingSizeH1"];
        this.stampingSizeH2 = data["stampingSizeH2"];
        this.stampingSizeH3 = data["stampingSizeH3"];
        this.stampingSizeH4 = data["stampingSizeH4"];
        this.windowId = data["windowId"];
        this.windowSizeH = data["windowSizeH"];
        this.windowSizeW = data["windowSizeW"];
        this.pasteId = data["pasteId"];
        this.pasteForm = data["pasteForm"];
        this.packingId = data["packingId"];
        this.inspectionId = data["inspectionId"];
        this.woodenId = data["woodenId"];
        this.woodenCode = data["woodenCode"];
        this.filmCode = data["filmCode"];
        this.customerProductCode = data["customerProductCode"];
        this.factoryId = data["factoryId"];
        this.pasteSpecialFormFlag = data["pasteSpecialFormFlag"];
        this.deliveryDistance = data["deliveryDistance"];
        this.otherExpense1 = data["otherExpense1"];
        this.otherWage1 = data["otherWage1"];
        this.otherUnitType1 = data["otherUnitType1"];
        this.otherExpense2 = data["otherExpense2"];
        this.otherWage2 = data["otherWage2"];
        this.otherUnitType2 = data["otherUnitType2"];
        this.otherExpense3 = data["otherExpense3"];
        this.otherWage3 = data["otherWage3"];
        this.otherUnitType3 = data["otherUnitType3"];
        this.shippingCostId = data["shippingCostId"];
        this.stampingPointsNumber = data["stampingPointsNumber"];
        this.shapeId = data["shapeId"];
        this.sheetSizeId = data["sheetSizeId"];
        this.sheetSizeWidth = data["sheetSizeWidth"];
        this.sheetSizeHeight = data["sheetSizeHeight"];
        this.sheetSizeGrain = data["sheetSizeGrain"];
        this.upperFlap = data["upperFlap"];
        this.insertion = data["insertion"];
        this.grain = data["grain"];
        this.developmentWidth = data["developmentWidth"];
        this.developmentHeight = data["developmentHeight"];
        this.groove = data["groove"];
        this.colorFText1 = data["colorFText1"];
        this.colorFText2 = data["colorFText2"];
        this.colorFText3 = data["colorFText3"];
        this.colorBText = data["colorBText"];
        this.itemCode = data["itemCode"];
        this.specialSizeFlag = data["specialSizeFlag"];
        this.specialDieCuttingNumberFlag = data["specialDieCuttingNumberFlag"];
        this.laminationPaperTypeBack = data["laminationPaperTypeBack"];
        this.laminationPaperTypeMedium = data["laminationPaperTypeMedium"];
        this.paperHeadApprovalFlag = data["paperHeadApprovalFlag"];
        this.surfaceF_varnishType = data["surfaceF_varnishType"];
        this.laminationPaperTypeFront = data["laminationPaperTypeFront"];
        this.laminationFrontThroughWage = data["laminationFrontThroughWage"];
        this.laminationFrontBasicWeight = data["laminationFrontBasicWeight"];
        this.laminationPaperTypeA = data["laminationPaperTypeA"];
        this.laminationAThroughWage = data["laminationAThroughWage"];
        this.laminationABasicWeight = data["laminationABasicWeight"];
        this.laminationPaperTypeB = data["laminationPaperTypeB"];
        this.laminationBThroughWage = data["laminationBThroughWage"];
        this.laminationBBasicWeight = data["laminationBBasicWeight"];
        this.cartonShippingType = data["cartonShippingType"];
        this.cartonTapeCutting = data["cartonTapeCutting"];
        this.cartonLinerCutting = data["cartonLinerCutting"];
        this.handProcessingFlag = data["handProcessingFlag"];
        this.waterRepellentFlag = data["waterRepellentFlag"];
        this.copyType = data["copyType"];
        this.embossingCode = data["embossingCode"];
        this.requestDesignFlag = data["requestDesignFlag"];
        this.bindingMethod = data["bindingMethod"];
        this.handPosition = data["handPosition"];
        this.specialUpperFlapFlag = data["specialUpperFlapFlag"];
        this.lowerFlap = data["lowerFlap"];
        this.specialLowerFlapFlag = data["specialLowerFlapFlag"];
        this.bindingNumber = data["bindingNumber"];
        this.stringColor = data["stringColor"];
        this.stringNumber = data["stringNumber"];
        this.handType = data["handType"];
        this.handSize = data["handSize"];
        this.otherMethod1 = data["otherMethod1"];
        this.otherMethod2 = data["otherMethod2"];
        this.otherNote1 = data["otherNote1"];
        this.otherNote2 = data["otherNote2"];
        this.otherNote3 = data["otherNote3"];
        this.specialNote1Flag = data["specialNote1Flag"];
        if (data["paper"] !== undefined) {
            this.paper = new MstPaper_model_1.MstPaper();
            this.paper.setMstPaper(data["paper"]);
        }
    };
    return ProductModel;
}(BaseModel_model_1.BaseModel));
exports.ProductModel = ProductModel;
//# sourceMappingURL=SF001_ProductInfo.js.map